services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    networks:
      - shieldwatch-network

  kafka:
    image: confluentinc/cp-kafka:7.4.4
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - shieldwatch-network
    depends_on:
      - zookeeper
    
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - shieldwatch-network
    volumes:
      - mongodb_data:/data/db


  threat-detection-service:
    build: ./threat_detection_service
    ports:
      - "3001:3001"
    networks:
      - shieldwatch-network
    environment:
      - KAFKA_BROKER=kafka:9092
      - MONGODB_URI=mongodb://mongodb:27017/threat-detection
      - PORT=3001
    depends_on:
      - kafka
      - mongodb

  incident-management-service:
    build: ./incident_management_service
    ports:
      - "3000:3000"
    networks:
      - shieldwatch-network
    environment:
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - threat-detection-service
      - kafka

  logging-service:
    build: ./logging_service
    ports:
      - "3002:3002"
    networks:
      - shieldwatch-network
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/logging
    depends_on:
      - mongodb

  notify-service:
    build: ./notify_service
    ports:
      - "3003:3003"
    networks:
      - shieldwatch-network
    environment:
      - SLACK_WEBHOOK_URL=https://hooks.slack.com/services/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

networks:
  shieldwatch-network:
    driver: bridge

volumes:
  mongodb_data: