services:
  zookeeper:
    image: zookeeper:3.7
    ports:
      - "2181:2181"
    networks:
      - kafka-network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - kafka-network
    
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - kafka-network
    volumes:
      - mongodb_data:/data/db

  incident-management-service:
    build: ./incident_management_service
    ports:
      - "3000:3000"
    networks:
      - kafka-network
    environment:
      - KAFKA_BROKER=kafka:9092

  threat-detection-service:
    build: ./threat_detection_service
    ports:
      - "3001:3001"
    networks:
      - kafka-network
    environment:
      - KAFKA_BROKER=kafka:9092

networks:
  kafka-network:
    driver: bridge

volumes:
  mongodb_data: