services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    networks:
      - shieldwatch-network

  kafka:
    image: confluentinc/cp-kafka:7.4.4
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - shieldwatch-network
    depends_on:
      - zookeeper
    
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - shieldwatch-network
    volumes:
      - mongodb_data:/data/db
    command: 
      - '--logpath'
      - '/var/log/mongodb/mongod.log'

  threat-detection-service:
    build: ./threat_detection_service
    volumes:
      - ./threat_detection_service:/usr/src/app
      - ignore:/usr/src/app/threat_detection_service/node_modules
    ports:
      - "3000:3000"
    networks:
      - shieldwatch-network
    environment:
      - KAFKA_BROKER=kafka:9092
      - MONGODB_URI=mongodb://mongodb:27017/threat-detection
      - PORT=3000
    depends_on:
      - kafka
      - mongodb

  incident-management-service:
    build: ./incident_management_service
    volumes:
      - ./incident_management_service:/usr/src/app
      - ignore:/usr/src/app/incident_management_service/node_modules
    ports:
      - "3001:3001"
    networks:
      - shieldwatch-network
    environment:
      - KAFKA_BROKER=kafka:9092
      - PORT=3001
    depends_on:
      - threat-detection-service
      - kafka

  auth-service:
    build: ./auth_service
    volumes:
      - ./auth_service:/usr/src/app
      - ignore:/usr/src/app/auth_service/node_modules
    ports:
      - "3002:3002"
    networks:
      - shieldwatch-network
    environment:
      - PORT=3002
      - ADMIN_LOGIN=${ADMIN_LOGIN}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}

  logging-service:
    build: ./logging_service
    volumes:
      - ./logging_service:/usr/src/app
      - ignore:/usr/src/app/logging_service/node_modules
    ports:
      - "3003:3003"
    networks:
      - shieldwatch-network
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/logging
      - PORT=3003
    depends_on:
      - mongodb
      - auth-service

  notify-service:
    build: ./notify_service
    volumes:
      - ./notify_service:/usr/src/app
      - ignore:/usr/src/app/notify_service/node_modules
    ports:
      - "3004:3004"
    networks:
      - shieldwatch-network
    environment:
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
      - PORT=3004

  gateway-service:
    build: ./gateway_service
    volumes:
      - ./gateway_service:/usr/src/app
      - ignore:/usr/src/app/gateway_service/node_modules
    ports:
      - "3005:3005"
    networks:
      - shieldwatch-network
    environment:
      - PORT=3005
    depends_on:
      - auth-service

  response-service:
    build: ./response_service
    volumes:
      - ./response_service:/usr/src/app
      - ignore:/usr/src/app/response_service/node_modules
    ports:
      - "3006:3006"
    networks:
      - shieldwatch-network
    environment:
      - KAFKA_BROKER=kafka:9092
      - PORT=3006
    depends_on:
      - kafka

networks:
  shieldwatch-network:
    driver: bridge

volumes:
  mongodb_data:
  ignore:
