services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    networks:
      - shieldwatch-network

  kafka:
    image: confluentinc/cp-kafka:7.4.4
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "events:1:1,responses:1:1"
    networks:
      - shieldwatch-network
    depends_on:
      - zookeeper
    healthcheck:
      test: kafka-topics --bootstrap-server kafka:9092 --list
      interval: 10s
      timeout: 10s
      retries: 5
    
    
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - shieldwatch-network
    volumes:
      - mongodb_data:/data/db
    command: 
      - '--logpath'
      - '/var/log/mongodb/mongod.log'
    healthcheck:
      test: ["CMD","mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5

  threat-detection-service:
    build: ./threat_detection_service
    volumes:
      - ./threat_detection_service:/usr/src/app
      - ignore:/usr/src/app/threat_detection_service/node_modules
    ports:
      - "3000" 
    networks:
      - shieldwatch-network
    environment:
      - KAFKA_BROKER=kafka:9092
      - MONGODB_URI=mongodb://mongodb:27017/threat-detection
      - PORT=3000
    healthcheck:
      test: curl --fail http://localhost:3000 || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
    depends_on:
      kafka:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    deploy: # load balancing
      replicas: 3

  incident-management-service:
    build: ./incident_management_service
    volumes:
      - ./incident_management_service:/usr/src/app
      - ignore:/usr/src/app/incident_management_service/node_modules
    ports:
      - "3001:3001"
    networks:
      - shieldwatch-network
    environment:
      - KAFKA_BROKER=kafka:9092
      - PORT=3001
      - LOGGING_SERVICE_URL=http://logging-service:3003/log
      - NOTIFY_SERVICE_URL=http://notify-service:3004/notify/slack
    healthcheck:
      test: curl --fail http://localhost:3001 || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
    depends_on:
      kafka:
        condition: service_healthy

  auth-service:
    build: ./auth_service
    volumes:
      - ./auth_service:/usr/src/app
      - ignore:/usr/src/app/auth_service/node_modules
    ports:
      - "3002:3002"
    networks:
      - shieldwatch-network
    environment:
      - PORT=3002
      - MONGODB_URI=mongodb://mongodb:27017/threat-detection
      - JWT_SECRET=${JWT_SECRET}
    healthcheck:
      test: curl --fail http://localhost:3002 || exit 1
      interval: 10s
      timeout: 10s
      retries: 5

  logging-service:
    build: ./logging_service
    volumes:
      - ./logging_service:/usr/src/app
      - ignore:/usr/src/app/logging_service/node_modules
    ports:
      - "3003:3003"
    networks:
      - shieldwatch-network
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/logging
      - PORT=3003
    healthcheck:
      test: curl --fail http://localhost:3003 || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
    depends_on:
      mongodb:
        condition: service_healthy
      auth-service:
        condition: service_healthy

  notify-service:
    build: ./notify_service
    volumes:
      - ./notify_service:/usr/src/app
      - ignore:/usr/src/app/notify_service/node_modules
    ports:
      - "3004:3004"
    networks:
      - shieldwatch-network
    environment:
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
      - PORT=3004
    healthcheck:
      test: curl --fail http://localhost:3004 || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
      

  response-service:
    build: ./response_service
    volumes:
      - ./response_service:/usr/src/app
      - ignore:/usr/src/app/response_service/node_modules
    ports:
      - "3006:3006"
    networks:
      - shieldwatch-network
    environment:
      - KAFKA_BROKER=kafka:9092
      - PORT=3006
    healthcheck:
      test: curl --fail http://localhost:3006 || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
    depends_on:
      kafka:
        condition: service_healthy

  gateway-service:
    build: ./gateway_service
    volumes:
      - ./gateway_service:/usr/src/app
      - ignore:/usr/src/app/gateway_service/node_modules
    ports:
      - "3005:3005"
    networks:
      - shieldwatch-network
    environment:
      - PORT=3005
    healthcheck:
      test: curl --fail http://localhost:3005 || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
    depends_on:
      auth-service:
        condition: service_healthy
      notify-service:
        condition: service_healthy
      incident-management-service:
        condition: service_healthy
      threat-detection-service:
        condition: service_healthy
      response-service:
        condition: service_healthy
    
  
  shieldwatch-client:
    build: ./shieldwatch-client
    ports:
      - "3000:3000"
    networks:
      - shieldwatch-network
    environment:
      - PORT=3000
    healthcheck:
      test: curl --fail http://localhost:3000 || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
    depends_on:
      gateway-service:
        condition: service_healthy
      
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"  # Le port public pour accéder au load balancer
    networks:
      - shieldwatch-network
    depends_on:
      - threat-detection-service
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

networks:
  shieldwatch-network:
    driver: bridge

volumes:
  mongodb_data:
  ignore:
